#!/usr/bin/python3

import json 
import requests
import sys

TOKEN = "464346603:AAHAq-oe-Qdhk8Dir9wHghaVgpq__JLTdF4"
URL = "https://api.telegram.org/bot{}/".format(TOKEN)
MESSAGE = sys.argv[1]


def get_url(url):
    response = requests.get(url)
    content = response.content.decode("utf8")
    return content


def get_json_from_url(url):
    content = get_url(url)
    js = json.loads(content)
    return js


def get_updates():
    url = URL + "getUpdates"
    js = get_json_from_url(url)
    return js


def get_last_chat_id(updates):
    num_updates = len(updates["result"])
    last_update = num_updates - 1
    chat_id = updates["result"][last_update]["message"]["chat"]["id"]
    return chat_id

def send_message(text, chat_id):
    url = URL + "sendMessage?text={}&chat_id={}".format(text, chat_id)
    get_url(url)
    

#chat = get_last_chat_id(get_updates())
#print(chat)
send_message(MESSAGE, -257742307)
